version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn bootstrap
          name: Run bootstrap
      - run:
          command: yarn build
          name: Build app

  # deploy: # this can be any name you choose
  #   executor: heroku/default
  #   steps:
  #     - attach_workspace:
  #         at: ~/project
  #     - heroku/deploy-via-git:
  #         force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git

workflows:
  test_my_app:
    jobs:
      - build_and_test
      # - deploy:
      #     requires:
      #       - build_and_test # only deploy if the build_and_test job has completed
      #     filters:
      #       branches:
      #         only: main # only deploy when on main
