version: "3.7"

services:
    mongodb:
        build:
            context: "./"
        logging:
            driver: none
        image: mongo
        ports: 
            - "27017:27017"
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ewqewq
        volumes:
            - ./data:/data/db
